//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public int productoId { get; set; }
        public Nullable<int> marcaId { get; set; }
        public Nullable<int> categoriaId { get; set; }
        public Nullable<int> proveedorId { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string volumen { get; set; }
        public string tipo { get; set; }
        public Nullable<bool> estado { get; set; }
        public string foto { get; set; }
    
        public virtual categorias categorias { get; set; }
        public virtual marcas marcas { get; set; }

        //public virtual proveedores proveedores { get; set; }
    }
}
